// app/layout.tsx
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import AppProvider from "@/Provider/AppProvider";
import { AuthProvider } from "@/context/auth-context";
// import QueryProvider from "./query-provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Drip Swag the pro in Promo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

<AuthProvider>


        <AppProvider>
        {/* <QueryProvider> */}
          
          {children}
          
          {/* </QueryProvider> */}
          </AppProvider>

          </AuthProvider>
      </body>
    </html>
  );
}
